# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define "master" do |master|
		master.vm.box = "bento/centos-8"
		master.vm.hostname = "master"
		master.vm.network :private_network, ip: "10.1.1.10"
		master.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.name = "Puppet Master"
		end
		master.vm.provision :shell, path: "centos-setup.sh"
	end

	config.vm.define "agent" do |agent|
		agent.vm.box = "bento/centos-8"
		agent.vm.hostname = "agent"
		agent.vm.network :private_network, ip: "10.1.1.11"
		agent.vm.provider "virtualbox" do |vb|
			vb.memory = "512"
			vb.name = "Puppet Agent"
		end
		agent.vm.provision :shell, path: "centos-setup.sh"
	end

	config.vm.define "webserver" do |webserver|
		webserver.vm.box = "bento/centos-8"
		webserver.vm.hostname = "webserver"
		webserver.vm.network :private_network, ip: "10.1.1.12"
		webserver.vm.provider "virtualbox" do |vb|
			vb.memory = "256"
			vb.name = "Puppet webserver"
		end
		webserver.vm.provision :shell, path: "centos-setup.sh"
	end

	config.vm.define "appserver" do |appserver|
		appserver.vm.box = "bento/centos-8"
		appserver.vm.hostname = "appserver"
		appserver.vm.network :private_network, ip: "10.1.1.13"
		appserver.vm.provider "virtualbox" do |vb|
			vb.memory = "256"
			vb.name = "Puppet appserver"
		end
		appserver.vm.provision :shell, path: "centos-setup.sh"
	end


end
